version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - thelper
    - testableexamples
    - usetesting
    - testifylint
    - gocritic
    - revive
    - gocognit
    - misspell
    - ineffassign
    - goconst
    - unparam
    - nestif
  disable:
    - errcheck
